require: rubocop-rspec
require: rubocop-rails

inherit_gem:
  relaxed-rubocop: .rubocop.yml

AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/bundle/**/*'
    - 'lib/solidus_cmd/templates/extension/**/*'
  TargetRubyVersion: 2.1
